name: Ionic Build and Upload
on: 
  push:
  workflow_dispatch:
   inputs:
      ip1: 
       description:  'input is 1'
       required: true
       
       
jobs:
  build-job:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3 
        with: 
          ref: ${{ github.event.inputs.ip1 }}
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with: 
          node-version: 16
          # Set always-auth in npmrc.
          
      - name: Install angular js and ionic 
        run:
          npm install -g @angular/cli
          npm install -g @ionic/cli
          npm ci
          ionic build --prod
          dir
          
          
